# Generated by Django 2.2.1 on 2019-05-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_buycar_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresource',
            name='small_money',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
