# Generated by Django 2.2.1 on 2019-05-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_address_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='receive',
            field=models.CharField(blank='True', max_length=32, null='True'),
        ),
    ]
