# Generated by Django 2.2.1 on 2019-05-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_auto_20190523_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
