# Generated by Django 2.2.1 on 2019-05-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_auto_20190529_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderresource',
            old_name='small_id',
            new_name='order_id',
        ),
    ]
